eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: bingo-cmdb:${spring.cloud.client.ipAddress}:${server.port}

server:
  port: 9000
spring:
  application:
    name: bingo-gateway
zuul:
  routes:
    ribbon1:
      path: /lb/**
      serviceId: bingo-lb
    ribbon2:
      path: /cmdb/**
      serviceId: bingo-cmdb
