eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: bingo-cmdb:${spring.cloud.client.ipAddress}:${server.port}

      # 将Instance ID设置成IP:端口的形式  参考https://github.com/spring-cloud/spring-cloud-netflix/issues/203